### ISSUE TITLE
Request : detect multiple patterns on screed

### ISSUE THREAD

**Issue by SuganNaickerf** [a31859/ImageDetectionDemoApp#5]
Hi, Nice project! Is there a way to detected multiple patterns at once and display the combined result?

**Comment by a31859** [comment]
Hello @SuganNaickerf, currently the plugin will only detect one visible pattern at the time. Only by changing the plugin code to account for multiple pattern at the same time that would be feasible. But I don't recommend doing that because it would increase the number of false detections since it's detecting the pattern by doing feature matching, without training, making it more prompt to false detections.

**Comment by SuganNaickerf** [comment]
OK. Thanks.
